# Generated by Django 4.0.4 on 2022-10-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(default=3)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('estimated_end', models.DateField()),
            ],
        ),
    ]
