# Generated by Django 4.0.4 on 2022-10-12 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoForm',
            new_name='Todo',
        ),
    ]
